global:
  scrape_interval:     3s



scrape_configs:
  - job_name: prometheus

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask-app'
    dns_sd_configs:
      - names: ['web']
        port: 5001
        type: A
        refresh_interval: 5s